name: Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style_check:
    name: SCSS Code Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lint
      - run: yarn format:check